export const sampleData = {
  personalInfo: {
    fullName: 'Alex Johnson',
    email: 'alex.johnson@email.com',
    phone: '+1 (555) 234-5678',
    linkedin: 'https://linkedin.com/in/alexjohnson',
    github: 'https://github.com/alexjohnson',
    location: 'San Francisco, CA',
    portfolio: 'https://alexjohnson.dev',
    jobTitle: 'Senior Full Stack Developer',
  },
  summary: 'Results-driven Senior Full Stack Developer with 7+ years of experience building scalable web applications and distributed systems. Proficient in JavaScript/TypeScript, React, Node.js, and cloud technologies (AWS, GCP). Passionate about clean code, performance optimization, and mentoring junior developers. Proven track record of delivering complex projects on time in agile environments.',
  skills: [
    { id: '1', category: 'Programming Languages', skills: 'JavaScript, TypeScript, Python, Java, Go' },
    { id: '2', category: 'Frontend', skills: 'React, Next.js, Vue.js, HTML5, CSS3, Tailwind CSS' },
    { id: '3', category: 'Backend', skills: 'Node.js, Express, FastAPI, Django, GraphQL, REST APIs' },
    { id: '4', category: 'Cloud & DevOps', skills: 'AWS, Docker, Kubernetes, CI/CD, Terraform, Jenkins' },
    { id: '5', category: 'Databases', skills: 'PostgreSQL, MongoDB, Redis, MySQL, Elasticsearch' },
    { id: '6', category: 'Tools & Practices', skills: 'Git, Agile/Scrum, TDD, Code Review, Microservices' },
  ],
  experience: [
    {
      id: '1',
      jobTitle: 'Senior Full Stack Developer',
      company: 'TechCorp Solutions',
      location: 'San Francisco, CA',
      startDate: 'Jan 2021',
      endDate: '',
      isPresent: true,
      bullets: [
        'Led development of a microservices-based e-commerce platform serving 2M+ users, improving system performance by 40%',
        'Architected and implemented real-time data pipeline using Kafka and Elasticsearch, reducing query latency by 60%',
        'Mentored team of 5 junior developers, conducted code reviews, and established best practices for React and Node.js development',
        'Collaborated with DevOps to migrate legacy monolith to AWS EKS, achieving 99.9% uptime SLA',
      ],
    },
    {
      id: '2',
      jobTitle: 'Full Stack Developer',
      company: 'StartupXYZ',
      location: 'Remote',
      startDate: 'Mar 2018',
      endDate: 'Dec 2020',
      isPresent: false,
      bullets: [
        'Built and maintained SaaS analytics dashboard using React and D3.js, used by 500+ enterprise clients',
        'Developed RESTful APIs with Node.js/Express, integrated with third-party services (Stripe, Twilio, SendGrid)',
        'Implemented CI/CD pipelines using GitHub Actions and Docker, reducing deployment time by 70%',
        'Optimized PostgreSQL database queries, resulting in 50% reduction in page load times',
      ],
    },
    {
      id: '3',
      jobTitle: 'Junior Software Developer',
      company: 'Digital Agency Co.',
      location: 'New York, NY',
      startDate: 'Jun 2016',
      endDate: 'Feb 2018',
      isPresent: false,
      bullets: [
        'Developed responsive web applications using React and Angular for 15+ client projects',
        'Collaborated with design team to implement pixel-perfect UI components',
        'Contributed to open-source projects and maintained internal component library',
      ],
    },
  ],
  education: [
    {
      id: '1',
      degree: 'Bachelor of Science in Computer Science',
      institution: 'University of California, Berkeley',
      location: 'Berkeley, CA',
      graduationDate: 'May 2016',
      gpa: '3.8/4.0',
      coursework: 'Data Structures, Algorithms, Operating Systems, Computer Networks, Database Systems, Software Engineering',
    },
  ],
  certifications: [
    {
      id: '1',
      name: 'AWS Certified Solutions Architect – Professional',
      organization: 'Amazon Web Services',
      dateObtained: 'Mar 2022',
      expirationDate: 'Mar 2025',
    },
    {
      id: '2',
      name: 'Certified Kubernetes Administrator (CKA)',
      organization: 'Cloud Native Computing Foundation',
      dateObtained: 'Nov 2021',
      expirationDate: 'Nov 2024',
    },
    {
      id: '3',
      name: 'Google Professional Cloud Developer',
      organization: 'Google Cloud',
      dateObtained: 'Jun 2023',
      expirationDate: '',
    },
  ],
  projects: [
    {
      id: '1',
      name: 'OpenSource Task Manager',
      technologies: 'React, Node.js, MongoDB, Socket.io, Docker',
      description: 'A real-time collaborative task management application with WebSocket support. Features include real-time updates, drag-and-drop kanban boards, team collaboration, and advanced filtering. Gained 1,200+ GitHub stars.',
      url: 'https://github.com/alexjohnson/task-manager',
    },
    {
      id: '2',
      name: 'ML Pipeline Automation Tool',
      technologies: 'Python, FastAPI, PostgreSQL, AWS SageMaker, Docker',
      description: 'An automated ML pipeline tool that streamlines model training, evaluation, and deployment. Integrated with AWS SageMaker for scalable training jobs. Used by 3 enterprise clients for production ML workflows.',
      url: 'https://github.com/alexjohnson/ml-pipeline',
    },
  ],
};
